<?php

use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            'name'=>'Marcelo',
            'email'=>'marcelo@bol.com.br',
            'password'=>bcrypt('123456'),
            'telefone'=>'3444-1640',
            'cpf'=>'1234567',
            'rg'=>'3445',
            'nivel_acesso'=>'2',
            'dtNascimento'=>'2000-10-10',
            'status'=>'A',
            'crm'=>'12321312',
            'especializacao_id'=>'1',
            'cracha'=>'d',
            'tratamento'=>'d',
            'alergico'=>'d',
            'convulsao'=>'d',
            'diabete'=>'d',
            'marcapasso'=>'d',
            'tipoSanguineo'=>'d',
            'responsavel_id'=>'1',

            ]);
            DB::table('users')->insert([
                'name'=>'Raiane',
                'email'=>'raiane@bol.com.br',
                'password'=>bcrypt('123456'),
                'telefone'=>'3444-1640',
                'cpf'=>'1234567',
                'rg'=>'34454555',
                'nivel_acesso'=>'3',
                'dtNascimento'=>'2000-10-10',
                'status'=>'A',
                'crm'=>'12321312',
            'especializacao_id'=>'1',
            'cracha'=>'d',
            'tratamento'=>'d',
            'alergico'=>'d',
            'convulsao'=>'d',
            'diabete'=>'d',
            'marcapasso'=>'d',
            'tipoSanguineo'=>'d',
            'responsavel_id'=>'1',

                ]);
                DB::table('users')->insert([
                    'name'=>'Roberto',
                    'email'=>'roberto@bol.com.br',
                    'password'=>bcrypt('123456'),
                    'telefone'=>'3444-1640',
                    'cpf'=>'1234567',
                    'rg'=>'3445',
                    'nivel_acesso'=>'3',
                    'dtNascimento'=>'2000-10-10',
                    'status'=>'A',
                    'crm'=>'12321312',
            'especializacao_id'=>'1',
            'cracha'=>'d',
            'tratamento'=>'d',
            'alergico'=>'d',
            'convulsao'=>'d',
            'diabete'=>'d',
            'marcapasso'=>'d',
            'tipoSanguineo'=>'d',
            'responsavel_id'=>'1',
                    ]);
                    DB::table('users')->insert([
                        'name'=>'Neusa',
                        'email'=>'neusa@bol.com.br',
                        'password'=>bcrypt('123456'),
                        'telefone'=>'3444-1640',
                        'cpf'=>'1234567',
                        'rg'=>'3445',
                        'nivel_acesso'=>'1',
                        'dtNascimento'=>'2000-10-10',
                        'status'=>'A',
                        'crm'=>'12321312',
                        'especializacao_id'=>'1',
                        'cracha'=>'d',
                        'tratamento'=>'d',
                        'alergico'=>'d',
                        'convulsao'=>'d',
                        'diabete'=>'d',
                        'marcapasso'=>'d',
                        'tipoSanguineo'=>'d',
                        'responsavel_id'=>'1',
                        ]);}
                    }
